# FUNCTION  are simple put a code block of instructions for
# computers to follow 

# built- in functions- a code black of
# instructions for a computer to follow 
# that was already written for us
# PRE WRITTEN CODE INSTRUCTIONS 

# input() - a built in function that allows us
# to print date in terminal.

name = input("what is your name? ")

# Date casting functions
# these are bulit in (pre written) functions 
# that change date types from one form into another
